GET http://localhost:5000/

###
POST http://localhost:5000/save
Content-Type: application/json

{"text":"Build static website"}

###
POST http://localhost:5000/save
Content-Type: application/json

{"text":"Build Responsive website"}


###
POST http://localhost:5000/save
Content-Type: application/json

{"text":"Solve medium question"}

###
PUT http://localhost:5000/update
Content-Type: application/json

{
    "_id":"67382a20784ece69f53717cd",
    "text":"Solve 2 medium questions"
}

###
DELETE  http://localhost:5000/delete/67383f7141ec1fcaffe4839c