POST http://localhost:5000/save
Content-Type: application/json

{
  "text": "Complete homework",
  "completed": false
}

###
POST http://localhost:5000/save
Content-Type: application/json

{
  "text": "Complete assignment",
  "completed": false
}

###
GET http://localhost:5000/

###
PUT http://localhost:5000/update
Content-Type: application/json

{
  "_id":"6753a53aecdcf488dbb94270",
  "text":"Completed Homework",
  "completed":true
}

###
DELETE http://localhost:5000/delete/6753a5e4ecdcf488dbb94275